---

- command: "docker run --rm -v /tmp:/stores k8smesos/mesos-pack:mesos_0.24.1-ubuntu1404_centos7"

# - copy: src=../images/mesosphere-el-repo-7-1.noarch.rpm dest=/tmp/mesosphere.rpm
# - shell: rpm -Uvh /tmp/mesosphere.rpm
# - yum: name=/tmp/mesosphere.rpm state=present
- yum: name={{item}} state=present
  with_items:
    # - mesos-0.24.1-0.2.35.centos701406
    - /tmp/mesos.rpm
    - ceph-common
