---

- include: ./centos.yml
  when: iscentos
- include: ./ubuntu.yml
  when: isubuntu

- copy: src=../images/pause.tar dest=/tmp/
- name: import docker images
  shell: docker load -i /tmp/pause.tar
  ignore_errors: True

- template: src=../templates/mesos-slave.j2 dest=/etc/default/mesos-slave
- shell: echo {{ipaddr}} | tee /etc/mesos-slave/ip
- shell: cp /etc/mesos-slave/ip /etc/mesos-slave/hostname
- service: name=mesos-slave state=restarted enabled=true
