---
- name: reload systemd daemon
  sudo: yes
  command: systemctl daemon-reload

- name: enable and start etcd
  sudo: yes
  service:
    name: etcd
    enabled: yes
    state: restarted

- name: restart skydns
  sudo: yes
  service:
    name: skydns
    enabled: yes
    state: restarted
