---

- apt: name={{item}} state=present
  with_items:
    - python-pip
  when: isubuntu

- yum: name=epel-release state=present
  when: iscentos

- yum: name={{item}} state=present
  with_items:
    - python-docker-py
  when: iscentos

- pip: name=docker-py state=present
  when: isubuntu
- template: src=../templates/docker.ubuntu.j2 dest=/etc/default/docker mode=0644
  when: isubuntu
- include: ./centos.yml
  when: iscentos
- service: name=docker state=restarted enabled=true
