---

- stat: path=/usr/local/bin/kubectl
  register: kubectl_installed
- command: "docker run --rm -v /tmp:/stores k8smesos/kubelet-pack:v1.1.2"
  when: not kubectl_installed.stat.exists
- shell: mv /tmp/kubectl /usr/local/bin/
  when: not kubectl_installed.stat.exists
- template: src=../../../addons/{{item}}.yaml.j2 dest=/tmp/{{item}}.yaml
  with_items:
    "{{deploy}}"
- shell: /usr/local/bin/kubectl create -f /tmp/{{item}}.yaml -s {{k8s_api_server_lb_url}}
  with_items:
    "{{deploy}}"
