- name: install kubernetes addons
  hosts: k8s_master
  sudo: yes
  vars:
    work_dir: /home/vagrant/certs
    username: testkey
  tasks:
    - name: copy ca
      copy:
        remote_src: yes
        src: /etc/kubernetes/certs/{{item}}
        dest: "{{work_dir}}/{{item}}"
      with_items:
        - ca.crt
        - ca.key

    - name: mkdir for working directory
      file:
        path: "{{work_dir}}"
        state: directory

    - shell: openssl genrsa -out test.key 2048
      args:
        chdir: "{{work_dir}}"

    - shell: openssl req -new -key test.key -subj "/CN={{username}}" -out test.csr
      args:
        chdir: "{{work_dir}}"

    - shell: openssl x509 -req -in test.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out test.crt -days 10000
      args:
        chdir: "{{work_dir}}"
