---
##########################################
# used docker images:
#   k8smesos/kubelet-pack:v1.1.8
#   skynetservices/skydns:2.5.3a
#   k8smesos/hyperkube:v1.1.8
#   zhpooer/podmaster:1.1
#   microbox/etcd:2.1.1
#   kubernetes/pause:latest

# mesos build depends:
#   mesoscloud/mesos-master:0.24.1-ubuntu-14.04
#   mesoscloud/zookeeper:3.4.6-ubuntu-14.04
#   ciscocloud/logstash:1.5.3, maybe
##########################################

- name: install common dependence
  # hosts: all:!localhost
  hosts: k8s_minion
  roles:
    - common      # TODO to download a rpm
    - collectd
    - logrotate   # TODO customize logrotate
    - consul-template # TODO to download a rpm
    - docker
    - consul      # TODO to download a rpm, comment pem file with command ca file add, set verify, adj distibutive
    - flannel     # TODO dail etcd url, flannel pkg
    #### - logstash
    - dnsmasq
    - etcd        #TODO etcd rpm


# - name: install kubernetes master
#   hosts: k8s_master
#   vars:
#     kube_users:
#       kube:
#         pass: root
#         role: admin
#       root:
#         pass: root
#         role: admin
#   roles:
#     - k8s-master

- name: install kubernetes master
  hosts: k8s_minion
  vars:
    network: flannel   # TODO: caligo surpport
  roles:
    - k8s-minion       # TODO: fluentd to collect logs?
    # - k8s-addons
