---

- name: install registry
  hosts: registry
  tasks:
    - name: install device-mapper-libs
      sudo: yes
      yum: name=device-mapper-libs

    - name: cp docker repo
      sudo: yes
      copy:
        dest: /etc/yum.repos.d/docker.repo
        content: |
          [dockerrepo]
          name=Docker Repository
          baseurl=https://yum.dockerproject.org/repo/main/centos/7
          enabled=1
          gpgcheck=1
          gpgkey=https://yum.dockerproject.org/gpg

    - name: install docker packages
      sudo: yes
      yum: name=docker-engine

    - name: enable and restart docker
      sudo: yes
      service:
        name: docker
        enabled: yes
        state: restarted

    - name: pull registry images
      sudo: yes
      command: docker pull registry:2.2.0

    - name: ensure registry conf dir exists
      sudo: yes
      file:
        path: /etc/docker_registry
        state: directory

    - name: copy registry conf file for proxy
      sudo: yes
      copy:
        dest: /etc/docker_registry/config.yml
        content: |
          version: 0.1
          log:
            level: debug
          http:
            addr: 0.0.0.0:5000
            debug:
              addr: 0.0.0.0:5001
          storage:
            filesystem:
              rootdirectory: /var/lib/registry
          proxy:
            remoteurl: https://registry-1.docker.io

    - name: run registry docker
      sudo: yes
      shell:
        "docker run -d -p 5000:5000 -p 5001:5001 --restart=always --name registry \
        -v /var/lib/registry:/var/lib/registry \
        -v /etc/docker_registry/config.yml:/etc/docker/registry/config.yml \
        registry:2.2.0"
