# - shell: wget https://storage.googleapis.com/kubernetes-release/release/v1.1.2/bin/linux/amd64/kubelet
# - shell: chmod a+x kubelet && mv kubelet /usr/local/bin/
- shell: mkdir -p /etc/kubernetes/manifests /srv/kubernetes/manifests
- template: src=../templates/mesos-cloud.cfg.j2 dest=/etc/kubernetes/manifests/mesos-cloud.cfg mode=0644
- template: src=../templates/podmaster.yaml.j2 dest=/etc/kubernetes/manifests/podmaster.yaml mode=0644
- template: src=../templates/kube-apiserver.yaml.j2 dest=/etc/kubernetes/manifests/kube-apiserver.yaml mode=0644
- template: src=../templates/kube-scheduler.yaml.j2 dest=/srv/kubernetes/manifests/kube-scheduler.yaml mode=0644
- template: src=../templates/kube-controller-manager.yaml.j2 dest=/srv/kubernetes/manifests/kube-controller-manager.yaml mode=0644

- shell: /usr/local/bin/kubelet --config=/etc/kubernetes/manifests