---

- name: install salt stack for salt master
  hosts: saltmaster
  sudo: yes
  vars:
    - salt_file_roots: /srv/salt/file/base
    - salt_pillar_roots: /srv/salt/pillar/base
  roles:
    - salt-master

- name: install salt stack for salt minion
  sudo: yes
  serial: 1
  hosts:
    - slave
    - master
    - saltmaster
  vars:
    - saltmaster: "{{groups['saltmaster'][0]}}"
  roles:
    - salt-minion

- name: set grains for master
  sudo: yes
  hosts: master
  tasks:
    - name: set the grains of master
      copy:
        dest: /etc/salt/grains
        content: |
          roles: master

    - name: restart salt minion
      service: name=salt-minion state=started
