---

- name: run zookeeper cluster
  hosts: zookeeper
  sudo: yes
  roles:
    - role: zookeeper

- name: start mesos master cluster
  hosts: mesosmaster
  sudo: yes
  roles:
    - role: mesos-master

- name: start mesos slave cluster
  hosts: mesosslave
  sudo: yes
  roles:
    - role: mesos-slave
