---

- name: create etcd data directories
  sudo: yes
  file:
    dest: "{{etcd_data_dir}}"
    state: directory
  tags: etcd

- name: install etcd for master
  sudo: yes
  yum:
    name: etcd-{{ etcd_version }}
    state: present
  when: "'etcd_master' in group_names"
  tags:
    - etcd

- name: create etcd master service override
  sudo: yes
  template:
    dest: "/usr/lib/systemd/system/etcd.service"
    src: etcd.master.service.j2
  when: "'etcd_master' in group_names"
  notify:
    - reload systemd daemon
    - enable and start etcd
  tags:
    - etcd

- name: ensure etcd image exists
  sudo: yes
  when: "not 'etcd_master' in group_names"
  command: docker pull {{ etcd_image }}:{{ etcd_image_tag }}

- name: create etcd master service override
  sudo: yes
  template:
    dest: "/usr/lib/systemd/system/etcd.service"
    src: etcd.proxy.service.j2
  when: "not 'etcd_master' in group_names"
  notify:
    - reload systemd daemon
    - enable and start etcd
  tags:
    - etcd

- name: install consul check script
  sudo: yes
  template:
    src: consul-check-etcd-member
    dest: /usr/local/bin
    mode: 0755
  when: consul_dc_group is defined
  tags:
    - etcd

- name: register etcd with consul
  sudo: yes
  copy:
    src: etcd-service.json
    dest: /etc/consul
  notify:
    - reload consul
  tags:
    - etcd

- include: skydns.yml

- name: enable and start etcd
  sudo: yes
  service:
    name: etcd
    enabled: yes
    state: started

- meta: flush_handlers
