---

- name: delete all k8s object
  hosts: k8_addons
  gather_facts: no
  tasks:
    - shell: /usr/local/bin/kubectl delete --all namespaces -s {{k8s_api_server_lb_url}}
      ignore_errors: True
    - shell: sleep 5

- name: stop kubelet
  hosts: kubernetes
  gather_facts: no
  sudo: yes
  tasks:
    - service: name=kubelet state=stopped
      ignore_errors: True

- name: clean mesos-slave
  sudo: yes
  gather_facts: no
  hosts: mesosslave
  tasks:
    - stat: path=/etc/init.d/mesos-slave
      register: service_status
    - service: name=mesos-slave state=stopped
      when: service_status.stat.exists is defined and service_status.stat.exists
    - shell: rm -fr /tmp/mesos/meta
    - shell: pkill km
      ignore_errors: True

- name: clean mesos master/slave, k8s
  hosts:
    - mesosmaster
    - mesosslave
    - kubernetes
  sudo: yes
  gather_facts: yes
  tasks:
    - shell: if [ `docker ps -a | wc -l` -gt 1 ]; then docker rm -f `docker ps -aq`; fi
    - shell: if [ `mount | grep mesos | grep rbd | wc -l` -gt 1 ]; then  umount `mount | grep mesos | grep rbd | awk '{print $3}'`; fi
    - shell: if [ `rbd showmapped | wc -l` -gt 1 ]; then rbd unmap /dev/rbd0; fi
      when: iscentos
    - shell: if [ `rbd showmapped | wc -l` -gt 1 ]; then rbd unmap /dev/rbd1; fi
      when: isubuntu

- name: rm zookeeper
  sudo: yes
  gather_facts: no
  hosts: zookeeper
  tasks:
    - shell: if [ `docker ps -f name=zookeeper | wc -l` -gt 1 ]; then docker rm -f zookeeper; fi

- name: rm etcd
  sudo: yes
  gather_facts: no
  hosts:
    - etcd
    - etcd_event
  tasks:
    - shell: if [ `docker ps -f name=etcd | wc -l` -gt 1 ]; then docker rm -f etcd; fi

- name: rm ceph lock
  sudo: yes
  gather_facts: no
  hosts: ceph
  tasks:
    - shell: if [ `rbd lock list mysql | wc -l` -gt 1 ]; then rbd lock remove mysql `rbd lock list mysql | awk '(NR>2){print $2}'` `rbd lock list mysql | awk '(NR>2){print $1}'`; fi

- name: rm influxdb
  sudo: yes
  hosts: influxdb
  gather_facts: no
  tasks:
    - shell: if [ `docker ps -f name=influxdb | wc -l` -gt 1 ]; then docker rm -f influxdb; fi
