---

- name: stop kubelet
  hosts: kubernetes
  sudo: yes
  tasks:
    - service: name=kubelet state=stopped
      ignore_errors: True

- name: clean mesos master/slave, k8s
  hosts:
    - mesosmaster
    - mesosslave
    - kubernetes
  sudo: yes
  tasks:
    - shell: if [ `docker ps -a | wc -l` -gt 1 ]; then docker rm -f `docker ps -aq`; fi
    - shell: if [ `rbd showmapped | wc -l` -gt 1 ]; then rbd unmap /dev/rbd1; fi


- name: rm zookeeper
  sudo: yes
  hosts: zookeeper
  tasks:
    - shell: if [ `docker ps -f name=zookeeper | wc -l` -gt 1 ]; then docker rm -f zookeeper; fi

- name: rm etcd
  sudo: yes
  hosts: etcd
  tasks:
    - shell: if [ `docker ps -f name=etcd | wc -l` -gt 1 ]; then docker rm -f etcd; fi

- name: rm ceph lock
  sudo: yes
  hosts: ceph
  tasks:
    - shell: if [ `rbd lock list mysql | wc -l` -gt 1 ]; then rbd lock remove mysql `rbd lock list mysql | awk '(NR>2){print $2}'` `rbd lock list mysql | awk '(NR>2){print $1}'`; fi
