---

- name: stop kubelet
  hosts: kubernetes
  sudo: yes
  tasks:
    - service: name=kubelet state=stopped

- name: clean mesos master/slave, k8s
  hosts:
    - mesosmaster
    - mesosslave
    - kubernetes
  sudo: yes
  tasks:
    - shell: docker rm -f `docker ps -aq`
