---

- name: stop kubelet
  hosts: kubernetes
  sudo: yes
  tasks:
    - service: name=kubelet state=stopped

- name: clean mesos master/slave, k8s
  hosts:
    - mesosmaster
    - mesosslave
    - kubernetes
  sudo: yes
  tasks:
    - shell: docker rm -f `docker ps -aq`

- name: rm zookeeper
  sudo: yes
  hosts: zookeeper
  tasks:
    - shell: docker rm -f zookeeper

- name: rm etcd
  sudo: yes
  hosts: etcd
  tasks:
    - shell: docker rm -f etcd
