---

- name: stop kubelet
  hosts: kubernetes
  sudo: yes
  tasks:
    - service: name=kubelet state=stopped

- name: clean mesos master/slave, k8s
  hosts:
    - mesosmaster
    - mesosslave
    - kubernetes
  sudo: yes
  tasks:
    - shell: if [ `docker ps -a | wc -l` -gt 1 ]; then echo ggg && docker rm -f `docker ps -aq`; fi

- name: rm zookeeper
  sudo: yes
  hosts: zookeeper
  tasks:
    - shell: if [ `docker ps -f name=zookeeper | wc -l` -gt 1 ]; then docker rm -f zookeeper; fi

- name: rm etcd
  sudo: yes
  hosts: etcd
  tasks:
    - shell: if [ `docker ps -f name=etcd | wc -l` -gt 1 ]; then docker rm -f etcd; fi
