---

- shell: mkdir -p /etc/haproxy
- template: src=../templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0644
- name: run haproxy
  docker:
    name: haproxy
    image: library/haproxy:1.6.2
    net: host
    state: started
    restart_policy: always
    volumes:
      - /etc/haproxy:/usr/local/etc/haproxy
