---

- include_vars: "{{ playbook_dir }}/roles/kubernetes/defaults/main.yml"

- include_vars: "{{ playbook_dir }}/roles/etcd/defaults/main.yml"

- name: Write kube-system namespace manifest
  sudo: yes
  copy:
    src=kube-system.yaml
    dest="{{ kube_manifest_tmpl_dir }}/kube-system.yaml"

- name: Create kube-system namespace
  sudo: yes
  kube:
    resource: namespace
    name: kube-system
    filename: "{{ kube_manifest_tmpl_dir }}/kube-system.yaml"
    state: present
    config: "{{ kube_config_dir }}/kubectl.kubeconfig"
  run_once: yes
  when: inventory_hostname == groups[k8s_master_group][0]
  tags:
    - addons

- include: skydns.yml

- include: kube-ui.yml
  when: enable_ui

# - include: logging.yml
#   when: enable_logging

# - include: monitoring.yml
#   when: enable_monitoring
