apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    security: s4
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
        "podAntiAffinity": {
          "requiredDuringSchedulingIgnoredDuringExecution": [{
            "labelSelector": {
              "matchExpressions": [{
                "key": "security",
                "operator": "In",
                "values":["s2"]
              }]
            },
            "topologyKey": "kubernetes.io/hostname"
          }]
        }
      }
    another-annotation-key: another-annotation-value
spec:
  containers:
  - name: with-newlabels
    image: gcr.io/google_containers/pause:2.0
