---

- name: reload daemon
  sudo: yes
  command: systemctl daemon-reload
  tags:
    - master

- name: restart kubelet
  sudo: yes
  service:
    name: kubelet
    state: restarted

- name: restart proxy
  sudo: yes
  service:
    name: kube-proxy
    state: restarted
