---
# tasks file for jmx-exporter

- name: pull tomcat
  sudo: yes
  command: docker pull library/tomcat:8.0

- name: rm tomcat
  sudo: yes
  shell: docker rm -f tomcat
  ignore_errors: true

- name: start tomcat
  sudo: yes
  shell: |
    docker run -d \
    -p 8888:8080 \
    -p {{jmx_port}}:{{jmx_port}} \
    --name tomcat \
    --env CATALINA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port={{jmx_port}} -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false" \
    tomcat:8.0

- name: pull docker jmx-exporter
  sudo: yes
  command: docker pull yagni/docker-jmx-exporter:0.7-SNAPSHOT

- name: make sure exporter conf dir exist
  sudo: yes
  file:
    dest: /etc/prometheus/exporter
    state: directory

- name: copy tomcat jmx exporter conf file
  sudo: yes
  template:
    src: tomcat.yml.j2
    dest: /etc/prometheus/exporter/tomcat.yml

- name: rm jmx-exporter container
  sudo: yes
  shell: docker rm -f jmx_exporter
  ignore_errors: true

- name: start jmx-exporter container
  sudo: yes
  command: |
    docker run -d \
    -v /etc/prometheus/exporter:/jmx_prometheus \
    -p {{exporter_port}}:9138 \
    --name jmx_exporter \
    yagni/docker-jmx-exporter:0.7-SNAPSHOT /jmx_prometheus/tomcat.yml
