---

- name: reload daemon
  sudo: yes
  command: systemctl daemon-reload
  tags:
    - master

- name: enable and restart kubelet
  sudo: yes
  service:
    enabled: yes
    name: kubelet
    state: restarted
  tags:
    - master

- name: restart proxy
  sudo: yes
  service:
    name: kube-proxy
    state: restarted
  tags:
    - master
