apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  labels:
    test: kubernetes
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - while true; do sleep 2; echo 2; done
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "kubernetes.io/quota"
      fsType: "xfs"
      options:
        volumeID: "vol1"
        size: "1000m"
        volumegroup: "kube_vg"
