- include: ./start_registry.yml
  when: step == "start_registry"

- include: ./start_registry_ro.yml
  when: step == "start_registry_ro"

- shell: if [ `docker ps | grep registry | wc -l` -gt 0 ]; then docker stop registry; fi
  when: step == "stop_registry"

- include: ./delete_blob.yml
  when: step == "delete_blob"

- include: ./collect_space.yml
  when: step == "collect_space"

- shell: rm -rf {{registry_storage}}
  when: step == "clean_registry"
