---

isubuntu: >
  {{ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'}}
iscentos: >
  {{ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'}}

vagrant_ip: >-
  {{ ansible_all_ipv4_addresses | last if iscentos | bool else ansible_all_ipv4_addresses[1] }}
private_ipv4: >-
  {{ vagrant_ip if ansible_virtualization_type == "virtualbox" else ansible_default_ipv4.address }}

consul_is_server: "{{inventory_hostname in groups[consul_servers_group]}}"
consul_dc: dc1

consul_advertise: "{{ private_ipv4 }}"
# consul_retry_join: "{% for host in groups[consul_servers_group] | intersect(groups[consul_dc_group]) %}\"{{ hostvars[host].private_ipv4 }}\"{% if not loop.last %}, {% endif %}{% endfor %}"
consul_retry_join: "{% for host in groups[consul_servers_group]  %}\"{{ host }}\"{% if not loop.last %}, {% endif %}{% endfor %}"
consul_bootstrap_expect: "{{ groups[consul_servers_group] | length }}"
consul_disable_remote_exec: yes
# consul_ca_file: ca.cert
# consul_cert_file: consul.cert
# consul_key_file: consul.key
# consul_acl_master_token: "89ff9d38-534a-41aa-a3a6-e4985bcd11c0"
# consul_acl_datacenter: "{{ consul_dc }}"
# consul_acl_default_policy: "allow"
# consul_acl_down_policy: "allow"
consul_dns_domain: consul
consul_verify_incoming: false
consul_verify_outgoing: false
consul_allow_stale: true
consul_max_stale: 5s
