---

- copy: src=../templates/docker.repo dest=/etc/yum.repos.d/docker.repo
- yum: name=epel-release state=present
- yum: name={{item}} state=present
  with_items:
    - docker-engine
    - device-mapper-libs
    - python-docker-py
- service: name=docker state=restarted enabled=true
