---

- name: stop k8s
  service: name={{item}} state=stopped
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy

- name: write the config files for api server
  sudo: yes
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - src: kubelet.service.j2
      dest: /usr/lib/systemd/system/kubelet.service
    - src: kube-proxy.service.j2
      dest: /usr/lib/systemd/system/kube-proxy.service

- name: reload daemon
  shell: systemctl daemon-reload
  tags:
    - master

- name: Enable kubernetes
  sudo: yes
  service:
    name: "{{item}}"
    enabled: yes
    state: restarted
  with_items:
    - kubelet
    - kube-proxy
