---

- name: install netcat
  sudo: yes
  yum:
    name: nmap-ncat
    state: present
  tags:
    - zookeeper
    - bootstrap

- name: install zookeeper scripts
  sudo: yes
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin
    mode: 0755
  with_items:
    - zookeeper_check.sh
    - zookeeper-wait-for-listen.sh
    - zookeeper_digest.sh
    # - zookeeper-update-mantl-0.5-0.6.sh
  tags:
    - zookeeper

- name: create zookeeper data directory
  sudo: yes
  file:
    path: /var/lib/zookeeper
    state: directory
  tags:
    - zookeeper

- name: create zookeeper env
  sudo: yes
  template:
    dest: /etc/sysconfig/zookeeper
    src: zookeeper.j2
  tags:
    - zookeeper

- name: ensure zookeeper docker image is present
  sudo: yes
  command: /usr/bin/docker pull {{ zookeeper_image }}:{{ zookeeper_image_tag }}
  tags:
    - zookeeper
    - bootstrap

- name: create zookeeper docker service
  sudo: yes
  template:
    dest: /usr/lib/systemd/system/zookeeper.service
    src: zookeeper.service.j2
  notify:
    - reload systemd daemon
    - enable and restart zookeeper

- name: generate zookeeper consul services
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: zk-consul.json.j2
      dest: /etc/consul/zk-consul.json
  notify:
    - reload consul
  tags:
    - zookeeper

- name: install zookeepercli package
  sudo: yes
  yum:
    name: https://github.com/outbrain/zookeepercli/releases/download/v1.0.10/zookeepercli-1.0.10-1.x86_64.rpm
    state: present
  tags:
    - zookeeper

- include: collectd.yml

- meta: flush_handlers

- include: distributive.yml
